### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by ntwrkguru**
Corrected spelling and made tweaks to conform to markdown standards

### CODE REVIEW

**Comment by travisghansen** [comment]
Thanks!  I think it's desired/ok to have multiple top-level headings. Is there a compelling reason to change that around?

I do like changing the first heading name and the spacing/spelling corrections.

**Comment by ntwrkguru** [comment]
The rationale was just that everything is a sub-section of the title, but since markdown doesn't have a title concept, I typically use an H1. I'm happy to revert. I also added blank lines around code blocks. Let me know and I can revert the H2 to H1 and H3 to H2, etc.

**Comment by travisghansen** [comment]
Yeah, let's pull back the heading level changes but leave everything else. Thanks!

**Comment by travisghansen** [comment]
Let's remove the `What is..` header now.

All headers after `Development` should be second level including the `release` header. Does that make sense?

**Comment by ntwrkguru** [comment]
I think so...like this?

**Comment by travisghansen** [comment]
Yes! Looks great although I'm going to miss `PersisitentVolumeClaim` ;)

**Pull request merged**
