### PR TITLE
support share ID vs lookup

### PR DESCRIPTION
**Pull request by travisghansen**
This makes the provisioner use legitmate nfs share IDs (upon creation and delete/lookup).

### CODE REVIEW

**Comment by travisghansen** [comment]
@nmaupu any chance you can pull/deploy/etc this MR?  After this one goes out I'd be open to spreading the word so to speak.  Thanks!

**Comment by travisghansen** [comment]
@nmaupu were new images built such that someone deploying fresh would get these changes?

**Comment by travisghansen** [comment]
@nmaupu any chance you can rebuild the images used by the manifests?

**Comment by nmaupu** [comment]
Hey! Somehow I though I already did but it seems it was not good. It's now done !
Version is 2.1:
```
$ docker run --rm docker.io/nmaupu/freenas-provisioner:2.1 --version
freenas-provisioner version v2.1
```

**Comment by travisghansen** [comment]
@nmaupu want to bump the manifests as well or would you like me to?

**Comment by nmaupu** [comment]
I already bumped the deployment
https://github.com/nmaupu/freenas-provisioner/blob/b86b58f0407b9293122cc8aa76f8098793380daa/deploy/deployment.yaml#L19

**Comment by travisghansen** [comment]
@nmaupu very cool, thanks!  Random question, but do you by chance also use pfSense?

**Comment by nmaupu** [comment]
I did by the past but not anymore, why ?

**Pull request merged**
